name: RAlentir
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06333
title: "Ralentir - Le temps d'un voyage autour du monde"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72120870-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#de0c71'
    - '#9b772d'
    - '#39201c'
    - '#2da7bc'
    - '#51e2fa'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.7030932423658669
  rhythmicContrast: 0.5
purpose: []
