name: Ralentir
favicon: null
layout_spectrum: 0
typography_spectrum: 0.05343
title: "Ralentir - Le temps d'un voyage autour du monde"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72120870-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4c0b4'
    - '#101211'
    - '#fefefe'
    - '#65625d'
    - '#393a35'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
