name: RAlentir
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05319
title: "Ralentir - Le temps d'un voyage autour du monde"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72120870-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4c0b4'
    - '#101211'
    - '#fefefe'
    - '#65625d'
    - '#393a35'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.7030932423658669
  rhythmicContrast: 0.5
purpose: []
